

export const nature = {
    "apport": "Apports (solaires, géothermiques, …)",
    "co2": "CO2",
    "consoasc": "Consommation ascenceur",
    "consoch": "Consommation aux ch",
    "consoecs": "Consommation aux ECS",
    "consofroid": "Consommation aux froid",
    "consobaie": "Consommation BAES",
    "consobur": "Consommation bureautique",
    "consocirc": "Consommation circulation et espaces communs",
    "consoelec": "Consommation d'électricité (globale)",
    "consogaz": "Consommation de gaz (globale)",
    "consoapnt": "Consommation du générateur d'appoint",
    "consobase": "Consommation du générateur de base",
    "consomen": "Consommation électroménager",
    "consoext": "Consommation extérieur",
    "consopark": "Consommation Parking",
    "consoserv": "Consommation serveur",
    "consotot": "Consommation totale",
    "consoocc": "Consommation zone d'occupation",
    "debit": "Débit",
    "detecpres": "Détecteur de présence",
    "directvent": "Direction du vent",
    "eclrmnt": "Eclairement",
    "enerutile": "Energie utile fournie par le générateur",
    "humidamb": "Humidité relative d'ambiance",
    "humidext": "Humidité relative extérieure",
    "pertebouc": "Pertes de bouclage",
    "pertedist": "Pertes de distribution",
    "pression": "Pression",
    "prodcogen": "Production co-génération",
    "prodecs": "Production ECS",
    "prodmeol": "Production micro éolien",
    "prodpvolt": "Production photovoltaïque",
    "prodprim": "Production primaire",
    "prodsec": "Production secondaire",
    "puisage": "Puisage",
    "raysol": "Rayonnement solaire",
    "tairextrait": "Tair extrait",
    "tairneuf": "Tair neuf",
    "tairrepris": "Tair repris",
    "tairsouf": "Tair soufflé",
    "tamb": "Température d'ambiance",
    "texter": "Température extérieure",
    "vitair": "Vitesse d'air",
    "vitvent": "Vitesse du vent"
}

export const statement = {
    "co2": "CO2",
    "cmptg": "Comptage",
    "conso": "Consommation",
    "cosphi": "Cos Phi",
    "debit": "Débit",
    "dirvent": "Direction du vent",
    "eclrmnt": "Eclairement",
    "humrel": "Humidité relative",
    "index": "Index",
    "intens": "Intensité",
    "press": "Pression",
    "prod": "Production",
    "puiss": "Puissance",
    "puissap": "Puissance apparente",
    "ray": "Rayonnement",
    "tchaud": "T Chaud",
    "tfroid": "T Froid",
    "temp": "Température",
    "tens": "Tension",
    "tour": "Tours",
    "vitair": "Vitesse d'air",
    "vol": "Volume"
}

export const unit = {
    "o": "(-)",
    "kw": "kW",
    "kwh": "kWh",
    "w": "W",
    "a": "A",
    "c": "°C",
    "pc": "%",
    "v": "V",
    "m3": "m3",
    "m3h": "m3/h",
    "ntour": "nb de tours",
    "deg": "(°)",
    "wm2": "W/m²",
    "ms": "m/s",
    "pa": "Pa",
    "bar": "bar",
    "ppm": "ppm",
    "npass": "nb de passages",
}

