
export const form = [
    { key: 'title', name: `Nom de l'opération`, required: true, type: 'text', },
    { key: 'abstract', name: 'Commentaires', type: 'textarea', },
    { key: 'program', name: 'Nom du programme', type: 'select', value: [ 'PREBAT', 'Autre' ] },
    { key: 'delivered_on', name: 'Année de livraison', type: 'number' },
    { key: 'contract_type', name: `Type de maîtrise d'ouvrage`, type: 'select', value: [
        'Etat',
        'Logements sociaux',
        'Particulier',
        'Privé',
        'Copropriété privée',
        'Autre',
    ] },
    { key: 'engineering', name: `Nature des travaux`, type: 'select', value: [ 'Neuf', 'Rénovation', 'Extension' ]},
    { key: 'label', name: 'Label / Certification', type: 'select', values: [
        'BBC Effinergie',
        'BBC Effinergie R',
        'Effinergie R',
        'PASSIVHAUS',
        'MINERGIE',
        'MINERGIE P',
        'MINERGIE Eco',
        'MINERGIE P Eco',
        'Effinergie +',
        'BEPOS Effinergie',
        'E0',
        'E1',
        'E2',
        'E3',
        'E4',
        'C0',
        'C1',
        'C2',
        'HQE',
        'BREEAM',
        'LEED',
        'H&E',
        'Démarche BDM',
        'Autre',
    ]},
    { key: 'air_permeability', name: `Pérméabilité à l'air des réseaux`, type: 'number'},
    { key: 'city_code', name: 'Commune', type: 'geocoder' }
]